name: pokeguess
services:

  discord-bot:
    build: ./
    restart: "unless-stopped"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - type: volume
        source: pokemonData
        target: /app/pokemons
    ports:
      - 8000:8000

volumes:
  pokemonData:
